default_language_version:
  python: python3.9

default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: no-commit-to-branch
      - id: end-of-file-fixer
        exclude: ^LICENSE|\.(html|csv|txt|svg)$
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys,--indent,"4"]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: \.(html|svg)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.3
    hooks:
      - id: ruff
        args:
         - --fix
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.28.0
    hooks:
      - id: commitizen
